name: GUI Debug Build/Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  gui_tests:

    runs-on: ubuntu-latest
    container:
      image: gleesus/decktricks

    steps:
    - uses: actions/checkout@v4

    - name: Build GUI Rust
      run: cargo build
      working-directory: ./gui/rust

    - name: Make build dir
      run: mkdir -p ./gui/godot/build

    - name: Copy Rust Lib to Godot
      run: cp ./gui/rust/target/debug/libdecktricks_godot_gui.so ./gui/godot/build

    - name: Build GUI
      run: godot --headless --export-debug Linux
      working-directory: ./gui/godot

    - name: Run GUI e2e scripts
      run: ./scripts/run_all_gui_e2e_tests.sh
