name: GUI Debug Build/Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  gui_tests:

    runs-on: ubuntu-latest
    container:
      image: gleesus/decktricks

    steps:
    - uses: actions/checkout@v4

    - name: whoami
      run: whoami

    - name: homedir
      run: echo ~

    - name: pwd
      run: pwd
