name: CLI Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cli_build_and_test:

    runs-on: ubuntu-latest
    container:
      image: gleesus/decktricks

    steps:
      - name: Preserve $HOME set in the container
        run: echo HOME=/root >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
      - name: Build CLI
        run: cargo build
      - name: Run Tests
        run: cargo test
